name: Publish Website

on:
  push:
    branches:
      - trunk
  workflow_dispatch:
jobs:
  Build-Artifact-Action:
    name: Build-Artifact-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: php-actions/composer@8a65f0d3c6a1d17ca4800491a40b5756a4c164f3 # v6.1.2
    - name: Upload the artifact
      uses: actions/upload-artifact@v4
      with:
        name: wpcom
        path: .
